# -*- coding: utf-8 -*-
"""ChuGyouk_PubMedQA_LLM_finetuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RKVmgapJGGkzSsDnGLpTxPP5Pzyek6tm

### ChuGyouk_PubMedQA 데이터셋을 활용한 LLM Finetuning
 - 4비트 사전 양자화된 모델"unsloth/Meta-Llama-3.1-8B" 활용

### LoRA 설정 (경량·속도 최적화형)
 - 목표: 작은 데이터셋 기준, VRAM 절약 + 빠른 학습 속도
 - r=8: LoRA 랭크 낮게 설정 → 적은 파라미터 학습, 과적합 방지
 - target_modules=["q_proj", "v_proj"]: 핵심 어텐션 부분만 학습 → 속도·메모리 절감
 - lora_alpha=16: LoRA 영향력 중간 수준 (기본 대비 안정적 수렴)
 - lora_dropout=0.05: 약간의 규제 효과로 일반화 향상
 - bias="none": 불필요한 bias 학습 비활성화
 - use_gradient_checkpointing="unsloth": GPU 메모리 절약, 긴 시퀀스 학습 가능
 - use_rslora=False: 안정성 모드는 해제 (속도 우선)
##### “LoRA r=8, q/v만 학습 — 메모리 절약형 설정 (Unsloth 체크포인트 활성화, 빠른 미세조정용)

### 프롬프트 & 종료 토큰
 - 목적: 모델이 학습 시 “질문 → 답변” 구조를 명확히 이해하고,
문장 끝에서 생성이 멈추도록 EOS 토큰을 추가함.
"""

from datasets import load_dataset

dataset = load_dataset(
    "ChuGyouk/PubMedQA-test-Ko",
    split="test",
    cache_dir="/content"  # 예: 구글 코랩이나 로컬 폴더
)

!pip install unsloth

!pip list

# Unsloth 라이브러리에서 FastLanguageModel을 임포트
from unsloth import FastLanguageModel
import torch

max_seq_length = 2048 # 최대 시퀀스 길이를 설정 ( 텍스트의 최대 길이를 지정)
dtype = None  # 자동 감지를 위해 None 설정. Tesla T4는 Float16, Ampere+는 Bfloat16 사용. 모델의 파라미터를 저장할 데이터 타입
load_in_4bit = True  # 메모리 사용량을 줄이기 위해 4비트 양자화 사용. 다만 양자화에 따른 손실이 있어서 필요에 따라 False로 설정 가능

# 4비트 사전 양자화된 모델 리스트 (더 빠른 다운로드 및 OOM 방지)
fourbit_models = [
    "unsloth/Meta-Llama-3.1-8B-bnb-4bit",      # Llama-3.1 8B 모델, 4비트 양자화
    "unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit",
    "unsloth/Meta-Llama-3.1-70B-bnb-4bit",
    "unsloth/Meta-Llama-3.1-405B-bnb-4bit",    # 405B 모델도 4비트 지원
    "unsloth/Mistral-Nemo-Base-2407-bnb-4bit", # Mistral 12B 모델, 4비트 지원
    "unsloth/Mistral-Nemo-Instruct-2407-bnb-4bit",
    "unsloth/mistral-7b-v0.3-bnb-4bit",        # Mistral v3 7B 모델, 4비트 지원
    "unsloth/mistral-7b-instruct-v0.3-bnb-4bit",
    "unsloth/Phi-3.5-mini-instruct",           # Phi-3.5 미니 인스트럭트 모델
    "unsloth/Phi-3-medium-4k-instruct",
    "unsloth/gemma-2-9b-bnb-4bit",
    "unsloth/gemma-2-27b-bnb-4bit",            # Gemma 2.27B 모델, 4비트 지원
] # 더 많은 모델은 https://huggingface.co/unsloth 에서 확인 가능

# 사전 학습된 모델과 토크나이저 로드
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Meta-Llama-3.1-8B",  # 사용할 모델 이름
    max_seq_length = max_seq_length,         # 설정한 최대 시퀀스 길이
    dtype = dtype,                           # 데이터 타입 설정
    load_in_4bit = load_in_4bit,             # 4비트 양자화 여부
)

# 목표: 메모리 절약 + 속도 중시
model = FastLanguageModel.get_peft_model(
    model,
    r = 8,   # 🔹 LoRA rank를 낮게 설정 — 작은 데이터셋엔 과적합 방지됨
    target_modules = ["q_proj", "v_proj"],  # 🔹 q/v projection만 학습 → 메모리 절감
    lora_alpha = 16,
    lora_dropout = 0.05,   # 약간의 regularization 효과
    bias = "none",
    use_gradient_checkpointing = "unsloth",  # 🔹 메모리 절약
    random_state = 3407,
    use_rslora = False,
    loftq_config = None,
)

alpaca_prompt = """아래에는 하나의 질문과 이에 대한 적절한 답변을 작성해야 하는 지시문이 있습니다.
지시문을 읽고, 요청에 가장 잘 맞는 답변을 한국어로 작성하세요.

### 지시문(Instruction):
{}

### 답변(Response):
{}"""

EOS_TOKEN = tokenizer.eos_token

from datasets import load_dataset
from transformers import TrainingArguments, Trainer, DataCollatorForLanguageModeling

# 1️⃣ 원본 데이터 로드
dataset = load_dataset("ChuGyouk/PubMedQA-test-Ko", split="test")

# 2️⃣ 앞에서 100개만 샘플링
dataset = dataset.select(range(100))
print(f"샘플 개수: {len(dataset)}")
print(dataset[0])

# 2️⃣ 프롬프트 변환
def format_prompt(example):
    instruction = example["QUESTION"]
    response = example["LONG_ANSWER"]
    text = alpaca_prompt.format(instruction, response) + EOS_TOKEN
    return {"text": text}

dataset = dataset.map(format_prompt)

# 3️⃣ 토크나이징
def tokenize(example):
    return tokenizer(
        example["text"],
        truncation=True,
        padding="max_length",
        max_length=2048,
    )

tokenized = dataset.map(tokenize, batched=True)

# 4️⃣ 데이터 정리
tokenized.set_format(type="torch", columns=["input_ids", "attention_mask"])

!pip install -U transformers accelerate peft trl

# 5️⃣ 학습 설정
training_args = TrainingArguments(
    output_dir="./finetuned_pubmedqa",
    num_train_epochs=3,
    per_device_train_batch_size=1,   # VRAM 한계에 따라 조정
    gradient_accumulation_steps=4,   # 배치 작을 때 효과적
    warmup_steps=50,
    save_steps=200,
    logging_steps=50,
    learning_rate=2e-4,
    fp16=True,                       # 4bit 양자화 모델은 필수
    optim="paged_adamw_8bit",        # 기울기 공간을 압축 (2~3배 절약)
    lr_scheduler_type="cosine",
    # evaluation_strategy="no",
    report_to="none"
)

# 6️⃣ 데이터 콜레이터 (언어모델 학습용)
data_collator = DataCollatorForLanguageModeling(tokenizer, mlm=False)

# 7️⃣ Trainer 설정
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized,
    data_collator=data_collator,
)

# 8️⃣ 파인튜닝 실행
trainer.train()

# 9️⃣ 학습 완료 후 저장
model.save_pretrained("./finetuned_pubmedqa_model")
tokenizer.save_pretrained("./finetuned_pubmedqa_model")